apiVersion: v1
kind: ConfigMap
metadata:
  name: rdrconfig
data:
  DRIVE_URL: {{ .Values.environment.DRIVE_URL | quote }}
  EMBED_APP_URL: {{ .Values.environment.EMBED_APP_URL | quote }}
  SRDR_URL: {{ .Values.environment.SRDR_URL | quote }}
  OWNCLOUD_CLIENT_ID: {{ .Values.environment.OWNCLOUD_CLIENT_ID | quote }}
  OWNCLOUD_CLIENT_SECRET: {{ .Values.environment.OWNCLOUD_CLIENT_SECRET | quote }}