apiVersion: v2
appVersion: ">0.2.5"
description: A single chart for a redis instance
name: redis-master
version: 1
type: application
keywords:
  - redis
  - minikube
dependencies:
  - name: redis-cluster
    alias: redis
    version: ^7.6.1
    repository: file://../redis-cluster
    condition: feature.redis
    tags:
      - storage
  - name: redis
    alias: redis-helper
    version: ^16.10.1
    repository: file://../redis
    condition: feature.redis
    tags:
      - storage